spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: ${SPRING_APPLICATION_NAME}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      database: ${SPRING_DATA_MONGODB_DATABASE}
  jackson:
    date-format: ${SPRING_JACKSON_DATE_FORMAT}
    serialization:
      indent-output: ${SPRING_JACKSON_SERIALIZATION_INDENT_OUTPUT}

server:
  port: ${SERVER_PORT}

path:
  to:
    auth: ${PATH_TO_AUTH}